<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Concerns\HasUuids;

/**
 * PhotoStrip
 *
 * Represents one saved, permanent photostrip.
 *
 * @property string   $id               UUID primary key
 * @property string   $frame_type       e.g. "classic-baby-pink"
 * @property string   $cloudinary_url   Full CDN URL of the JPEG
 * @property string   $cloudinary_id    Cloudinary public_id (for deletes)
 * @property string   $qr_url           api.qrserver.com URL for the QR PNG
 * @property bool     $has_date         Whether the date overlay was applied
 * @property bool     $has_time         Whether the time overlay was applied
 * @property bool     $is_public        Show in gallery? (user opt-in)
 * @property int      $likes            Accumulated like count
 * @property int      $download_count   Accumulated download count
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 */
class PhotoStrip extends Model
{
    use HasUuids;

    protected $table = 'photo_strips';

    /**
     * UUIDs are generated by the controller before insert, but HasUuids will
     * auto-generate one if the key is missing.
     */
    protected $keyType    = 'string';
    public    $incrementing = false;

    protected $fillable = [
        'id',
        'frame_type',
        'cloudinary_url',
        'cloudinary_id',
        'qr_url',
        'has_date',
        'has_time',
        'is_public',
        'likes',
        'download_count',
    ];

    protected $casts = [
        'has_date'       => 'boolean',
        'has_time'       => 'boolean',
        'is_public'      => 'boolean',
        'likes'          => 'integer',
        'download_count' => 'integer',
    ];

    // ── Scopes ──────────────────────────────────────────────

    /** Only publicly-shared strips */
    public function scopePublic($query)
    {
        return $query->where('is_public', true);
    }

    /** Filter by frame slug */
    public function scopeForFrame($query, string $frame)
    {
        return $query->where('frame_type', $frame);
    }
}